apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/julianZeilinger/mlops-infrastructure"
    path: "framework-tests/mlflow/components"
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mlflow
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
