apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: postgresql
    targetRevision: 16.4.6
    helm:
      values: |
        fullnameOverride: postgres
        auth:
          postgresPassword: lakefs-secret
          username: lakefs
          password: lakefs-secret
          database: lakefs
        persistence:
          enabled: true
          storageClass: "standard"  # Passen Sie diesen Wert an Ihre Umgebung an
          size: 8Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgresql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true