apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "registry-1.docker.io/bitnamicharts"
    chart: postgresql
    targetRevision: 16.4.6
    helm:
      values: |
        auth:
          enabledPostgresUser: true
          user: "user"
          password: "lakefs"
          database: "lakefs"
          postgresPassword: "lakefs"
          replicationPassword: "lakefs"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
