apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: postgresql
    targetRevision: "16.4.6"
    helm:
      values: |
        fullnameOverride: postgres
        auth:
          username: lakefs
          password: lakefs-secret
          database: lakefs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: lakefs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true