apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: minio
    targetRevision: 14.8.4
    helm:
      values: |
        # Überschreiben Sie hier die Standardwerte des Charts
        auth:
          accessKey: minio
          secretKey: minio123
        service:
          type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
