apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: minio
    targetRevision: 14.8.4
    helm:
      values: |
        service:
          type: LoadBalancer
          ports:
            api: 8080
            console: 80
        provisioning:
          users:
            - username: user1
              password: password1
              disabled: false
              policies:
                - readwrite
            - username: user2
              password: password2
              disabled: false
              policies:
                - readonly
              setPolicies: true
            - username: admin
              password: adminpassword
              disabled: false
              policies:
                - consoleAdmin
              setPolicies: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
