apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: minio
    targetRevision: 14.8.4
    helm:
      values: |
        auth:
          rootUser: minio-admin
          rootPassword: minio-secret-password
        service:
          type: LoadBalancer
          ports:
            api: 80
            console: 443
        provisioning:
          networkPolicy:
            enabled: false
        networkPolicy:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
