apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: default
  source:
    chart: minio
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: HEAD
    helm:
      valuesObject:
        auth:
          accessKey: minio
          secretKey: minio123
  destination:
    name: "minio"
    namespace: mlflow
