apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: mlflow
    targetRevision: 2.1.0
    helm:
      values: |
        # Überschreiben Sie hier die Standardwerte des Charts
        persistence:
          enabled: true
        tracking:
          auth:
            enabled: true
            username: admin
            password: admin
          service:
            type: LoadBalancer
            ports:
              http: 5000
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
