apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakefs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.lakefs.io"
    chart: lakefs
    targetRevision: 1.3.33
    helm:
      values: |
        secrets:
          authEncryptSecretKey: "my-random-secret-key"
        lakefsConfig: |
          server:
            listen_addr: ":8000"
          database:
            type: local
          blockstore:
            type: s3
            signing:
              key: "my-random-secret-key"
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              credentials:
                access_key_id: iRuq4AehO6MJjZpkTkD4
                secret_access_key: Pyf17ITMrmWrMzHFXiHBNTDxle2rSiC9myzhPGS9

  destination:
    server: "https://kubernetes.default.svc"
    namespace: lakefs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
