apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakefs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.lakefs.io"
    chart: lakefs
    targetRevision: 1.3.33
    helm:
      values: |
        secrets:
          databaseConnectionString: "postgres://lakefs:lakefs-secret@postgres.lakefs.svc.cluster.local:5432/lakefs?sslmode=disable"
          authEncryptSecretKey: "my-random-secret-key"
        lakefsConfig: |
          server:
            listen_addr: ":8000"
          database:
            type: postgres
          blockstore:
            type: s3
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              access_key_id: minio-admin
              secret_access_key: minio-secret-password
              bucket: lakefs
              ssl: false
          gateways:
            s3:
              domain_name: s3.lakefs.example.com

  destination:
    server: "https://kubernetes.default.svc"
    namespace: lakefs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
