apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakefs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.lakefs.io"
    chart: lakefs
    targetRevision: 1.3.33
    helm:
      values: |
        secrets:
          authEncryptSecretKey: "my-random-secret-key"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          hosts:
            - host: "lakefs.kubeflow.com"
              paths: /
        lakefsConfig: |
          listen_address: ":8000"
          database:
            type: "postgres"
            postgres:
              connection_string: "postgres://postgres:lakefs@postgres-postgresql.postgres.svc.cluster.local:5432/lakefs?sslmode=disable"
          blockstore:
            type: s3
            s3:
              force_path_style: true
              discover_bucket_region: false
              endpoint: "http://minio.minio.svc.cluster.local:9000"
              credentials:
                access_key_id: 53F1IakE0QkKEB4x6urQ
                secret_access_key: 8lrKVluRMc4ASgL4RNAbOEiGWEvvbB4GDuLs0ZKh

  destination:
    server: "https://kubernetes.default.svc"
    namespace: lakefs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
