apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakefs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.lakefs.io"
    chart: lakefs
    targetRevision: 1.3.33
    helm:
      values: |
        secrets:
          authEncryptSecretKey: "my-random-secret-key"
        lakefsConfig: |
          listen_address: ":8000"
          database:
            type: local
          blockstore:
            type: s3
            signing:
              secret_key: "my-random-secret-key"
            s3:
              endpoint: "https://minio.minio.svc.cluster.local:9000"
              credentials:
                access_key_id: 53F1IakE0QkKEB4x6urQ
                secret_access_key: 8lrKVluRMc4ASgL4RNAbOEiGWEvvbB4GDuLs0ZKh
                use_ssl: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: lakefs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
